//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPCAppp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterCommunicationTrace
    {
        public int Id { get; set; }
        public string ComponentCode { get; set; }
        public Nullable<System.Guid> InternalRefId { get; set; }
        public string VendorRefId { get; set; }
        public int RequestForId { get; set; }
        public bool IsOutBoundCall { get; set; }
        public int IntegratiorVendorTypeId { get; set; }
        public string RequestURL { get; set; }
        public Nullable<int> PortNumber { get; set; }
        public string RequestJson { get; set; }
        public string ResponseJson { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public string StatusCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
