//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPCAppp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorArea { get; set; }
        public string StackTrace { get; set; }
        public string ComponentCode { get; set; }
        public bool IsEmailSent { get; set; }
        public int FailedCount { get; set; }
    }
}
